<?php
    $filename = DOL_DOCUMENT_ROOT . '/custom/etatscomptables/DotationImobilisation/Dotationimobilisation_fichier_' . $annee_du . '.php';
    if (file_exists($filename)) {
        include $filename;
        
        $ValeursTableau = $dom->createElement('ValeursTableau');
        $groupeValeursTableau->appendChild($ValeursTableau);
        $tableau = $dom->createElement('tableau');
        $ValeursTableau->appendChild($tableau);
        $id = $dom->createElement('id','12');
        $tableau->appendChild($id);
        $groupeValeurs = $dom->createElement('groupeValeurs');
        $ValeursTableau->appendChild($groupeValeurs);

   
        $i=1;
        CodeEdiValeurCelluleLigne('10061', 'Frais de constitution', $i);
        CodeEdiValeurCelluleLigne('1078', $dotationimobilisation0, $i);
        CodeEdiValeurCelluleLigne('1079', $dotationimobilisation1, $i);
        CodeEdiValeurCelluleLigne('1080', $dotationimobilisation2, $i);
        CodeEdiValeurCelluleLigne('1081', $dotationimobilisation3, $i);
        CodeEdiValeurCelluleLigne('1082', $dotationimobilisation4, $i);
        CodeEdiValeurCelluleLigne('1083', $dotationimobilisation5, $i);
        CodeEdiValeurCelluleLigne('1084',$dotationimobilisation6, $i);
        CodeEdiValeurCelluleLigne('1085',$cumul1, $i);
        CodeEdiValeurCelluleLigne('1086', $dotationimobilisation7, $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Frais prealables au demarrage', $i);
        CodeEdiValeurCelluleLigne('1078', $dotationimobilisation8, $i);
        CodeEdiValeurCelluleLigne('1079', $dotationimobilisation9, $i);
        CodeEdiValeurCelluleLigne('1080', $dotationimobilisation10, $i);
        CodeEdiValeurCelluleLigne('1081', $dotationimobilisation11, $i);
        CodeEdiValeurCelluleLigne('1082', $dotationimobilisation12, $i);
        CodeEdiValeurCelluleLigne('1083', $dotationimobilisation13, $i);
        CodeEdiValeurCelluleLigne('1084',$dotationimobilisation14, $i);
        CodeEdiValeurCelluleLigne('1085',$cumul2, $i);
        CodeEdiValeurCelluleLigne('1086', $dotationimobilisation15, $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Frais d \'augmentation du capital', $i);
        CodeEdiValeurCelluleLigne('1078', $dotationimobilisation16, $i);
        CodeEdiValeurCelluleLigne('1079', $dotationimobilisation17, $i);
        CodeEdiValeurCelluleLigne('1080', $dotationimobilisation18, $i);
        CodeEdiValeurCelluleLigne('1081', $dotationimobilisation19, $i);
        CodeEdiValeurCelluleLigne('1082', $dotationimobilisation20, $i);
        CodeEdiValeurCelluleLigne('1083', $dotationimobilisation21, $i);
        CodeEdiValeurCelluleLigne('1084',$dotationimobilisation22, $i);
        CodeEdiValeurCelluleLigne('1085',$cumul3, $i);
        CodeEdiValeurCelluleLigne('1086', $dotationimobilisation23, $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Frais operations de fusions, scissions', $i);
        CodeEdiValeurCelluleLigne('1078', $dotationimobilisation24, $i);
        CodeEdiValeurCelluleLigne('1079', $dotationimobilisation25, $i);
        CodeEdiValeurCelluleLigne('1080', $dotationimobilisation26, $i);
        CodeEdiValeurCelluleLigne('1081', $dotationimobilisation27, $i);
        CodeEdiValeurCelluleLigne('1082', $dotationimobilisation28, $i);
        CodeEdiValeurCelluleLigne('1083', $dotationimobilisation29, $i);
        CodeEdiValeurCelluleLigne('1084',$dotationimobilisation30, $i);
        CodeEdiValeurCelluleLigne('1085',$cumul4, $i);
        CodeEdiValeurCelluleLigne('1086', $dotationimobilisation31, $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Frais de prospection', $i);
        CodeEdiValeurCelluleLigne('1078', $dotationimobilisation32, $i);
        CodeEdiValeurCelluleLigne('1079', $dotationimobilisation33, $i);
        CodeEdiValeurCelluleLigne('1080', $dotationimobilisation34, $i);
        CodeEdiValeurCelluleLigne('1081', $dotationimobilisation35, $i);
        CodeEdiValeurCelluleLigne('1082', $dotationimobilisation36, $i);
        CodeEdiValeurCelluleLigne('1083', $dotationimobilisation37, $i);
        CodeEdiValeurCelluleLigne('1084',$dotationimobilisation38, $i);
        CodeEdiValeurCelluleLigne('1085',$cumul5, $i);
        CodeEdiValeurCelluleLigne('1086', $dotationimobilisation39, $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Frais de publicite', $i);
        CodeEdiValeurCelluleLigne('1078', $dotationimobilisation40, $i);
        CodeEdiValeurCelluleLigne('1079', $dotationimobilisation41, $i);
        CodeEdiValeurCelluleLigne('1080', $dotationimobilisation42, $i);
        CodeEdiValeurCelluleLigne('1081', $dotationimobilisation43, $i);
        CodeEdiValeurCelluleLigne('1082', $dotationimobilisation44, $i);
        CodeEdiValeurCelluleLigne('1083', $dotationimobilisation45, $i);
        CodeEdiValeurCelluleLigne('1084',$dotationimobilisation46, $i);
        CodeEdiValeurCelluleLigne('1085',$cumul6, $i);
        CodeEdiValeurCelluleLigne('1086', $dotationimobilisation47, $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Autres frais preliminaires', $i);
        CodeEdiValeurCelluleLigne('1078', $dotationimobilisation48, $i);
        CodeEdiValeurCelluleLigne('1079', $dotationimobilisation49, $i);
        CodeEdiValeurCelluleLigne('1080', $dotationimobilisation50, $i);
        CodeEdiValeurCelluleLigne('1081', $dotationimobilisation51, $i);
        CodeEdiValeurCelluleLigne('1082', $dotationimobilisation52, $i);
        CodeEdiValeurCelluleLigne('1083', $dotationimobilisation53, $i);
        CodeEdiValeurCelluleLigne('1084',$dotationimobilisation54, $i);
        CodeEdiValeurCelluleLigne('1085',$cumul7, $i);
        CodeEdiValeurCelluleLigne('1086', $dotationimobilisation55, $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Frais d\'acquisition des immobilisations', $i);
        CodeEdiValeurCelluleLigne('1078', $dotationimobilisation56, $i);
        CodeEdiValeurCelluleLigne('1079', $dotationimobilisation57, $i);
        CodeEdiValeurCelluleLigne('1080', $dotationimobilisation58, $i);
        CodeEdiValeurCelluleLigne('1081', $dotationimobilisation59, $i);
        CodeEdiValeurCelluleLigne('1082', $dotationimobilisation60, $i);
        CodeEdiValeurCelluleLigne('1083', $dotationimobilisation61, $i);
        CodeEdiValeurCelluleLigne('1084',$dotationimobilisation62, $i);
        CodeEdiValeurCelluleLigne('1085',$cumul8, $i);
        CodeEdiValeurCelluleLigne('1086', $dotationimobilisation63, $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Frais d\'emission des emprunts', $i);
        CodeEdiValeurCelluleLigne('1078', $dotationimobilisation64, $i);
        CodeEdiValeurCelluleLigne('1079', $dotationimobilisation65, $i);
        CodeEdiValeurCelluleLigne('1080', $dotationimobilisation66, $i);
        CodeEdiValeurCelluleLigne('1081', $dotationimobilisation67, $i);
        CodeEdiValeurCelluleLigne('1082', $dotationimobilisation68, $i);
        CodeEdiValeurCelluleLigne('1083', $dotationimobilisation69, $i);
        CodeEdiValeurCelluleLigne('1084',$dotationimobilisation70, $i);
        CodeEdiValeurCelluleLigne('1085',$cumul9, $i);
        CodeEdiValeurCelluleLigne('1086', $dotationimobilisation71, $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', ' Autres charges à repartir', $i);
        CodeEdiValeurCelluleLigne('1078', $dotationimobilisation72, $i);
        CodeEdiValeurCelluleLigne('1079', $dotationimobilisation73, $i);
        CodeEdiValeurCelluleLigne('1080', $dotationimobilisation74, $i);
        CodeEdiValeurCelluleLigne('1081', $dotationimobilisation75, $i);
        CodeEdiValeurCelluleLigne('1082', $dotationimobilisation76, $i);
        CodeEdiValeurCelluleLigne('1083', $dotationimobilisation77, $i);
        CodeEdiValeurCelluleLigne('1084',$dotationimobilisation78, $i);
        CodeEdiValeurCelluleLigne('1085',$cumul10, $i);
        CodeEdiValeurCelluleLigne('1086', $dotationimobilisation79, $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', ' Primes de remboursement des obligations', $i);
        CodeEdiValeurCelluleLigne('1078', $dotationimobilisation80, $i);
        CodeEdiValeurCelluleLigne('1079', $dotationimobilisation81, $i);
        CodeEdiValeurCelluleLigne('1080', $dotationimobilisation82, $i);
        CodeEdiValeurCelluleLigne('1081', $dotationimobilisation83, $i);
        CodeEdiValeurCelluleLigne('1082', $dotationimobilisation84, $i);
        CodeEdiValeurCelluleLigne('1083', $dotationimobilisation85, $i);
        CodeEdiValeurCelluleLigne('1084',$dotationimobilisation86, $i);
        CodeEdiValeurCelluleLigne('1085',$cumul11, $i);
        CodeEdiValeurCelluleLigne('1086', $dotationimobilisation87, $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', ' Immob en recherche et developpement', $i);
        CodeEdiValeurCelluleLigne('1078', $dotationimobilisation88, $i);
        CodeEdiValeurCelluleLigne('1079', $dotationimobilisation89, $i);
        CodeEdiValeurCelluleLigne('1080', $dotationimobilisation90, $i);
        CodeEdiValeurCelluleLigne('1081', $dotationimobilisation91, $i);
        CodeEdiValeurCelluleLigne('1082', $dotationimobilisation92, $i);
        CodeEdiValeurCelluleLigne('1083', $dotationimobilisation93, $i);
        CodeEdiValeurCelluleLigne('1084',$dotationimobilisation94, $i);
        CodeEdiValeurCelluleLigne('1085',$cumul12, $i);
        CodeEdiValeurCelluleLigne('1086', $dotationimobilisation95, $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Terrains nus', $i);
        CodeEdiValeurCelluleLigne('1078', $dotationimobilisation96, $i);
        CodeEdiValeurCelluleLigne('1079', $dotationimobilisation97, $i);
        CodeEdiValeurCelluleLigne('1080', $dotationimobilisation98, $i);
        CodeEdiValeurCelluleLigne('1081', $dotationimobilisation99, $i);
        CodeEdiValeurCelluleLigne('1082', $dotationimobilisation100, $i);
        CodeEdiValeurCelluleLigne('1083', $dotationimobilisation101, $i);
        CodeEdiValeurCelluleLigne('1084',$dotationimobilisation102, $i);
        CodeEdiValeurCelluleLigne('1085',$cumul13, $i);
        CodeEdiValeurCelluleLigne('1086', $dotationimobilisation103, $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Terrains amenages', $i);
        CodeEdiValeurCelluleLigne('1078', $dotationimobilisation104, $i);
        CodeEdiValeurCelluleLigne('1079', $dotationimobilisation105, $i);
        CodeEdiValeurCelluleLigne('1080', $dotationimobilisation106, $i);
        CodeEdiValeurCelluleLigne('1081', $dotationimobilisation107, $i);
        CodeEdiValeurCelluleLigne('1082', $dotationimobilisation108, $i);
        CodeEdiValeurCelluleLigne('1083', $dotationimobilisation109, $i);
        CodeEdiValeurCelluleLigne('1084',$dotationimobilisation110, $i);
        CodeEdiValeurCelluleLigne('1085',$cumul14, $i);
        CodeEdiValeurCelluleLigne('1086', $dotationimobilisation111, $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Terrains batis', $i);
        CodeEdiValeurCelluleLigne('1078', $dotationimobilisation112, $i);
        CodeEdiValeurCelluleLigne('1079', $dotationimobilisation113, $i);
        CodeEdiValeurCelluleLigne('1080', $dotationimobilisation114, $i);
        CodeEdiValeurCelluleLigne('1081', $dotationimobilisation115, $i);
        CodeEdiValeurCelluleLigne('1082', $dotationimobilisation116, $i);
        CodeEdiValeurCelluleLigne('1083', $dotationimobilisation117, $i);
        CodeEdiValeurCelluleLigne('1084',$dotationimobilisation118, $i);
        CodeEdiValeurCelluleLigne('1085',$cumul15, $i);
        CodeEdiValeurCelluleLigne('1086', $dotationimobilisation119, $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Agencements et amenagements de terrains', $i);
        CodeEdiValeurCelluleLigne('1078', $dotationimobilisation120, $i);
        CodeEdiValeurCelluleLigne('1079', $dotationimobilisation121, $i);
        CodeEdiValeurCelluleLigne('1080', $dotationimobilisation122, $i);
        CodeEdiValeurCelluleLigne('1081', $dotationimobilisation123, $i);
        CodeEdiValeurCelluleLigne('1082', $dotationimobilisation124, $i);
        CodeEdiValeurCelluleLigne('1083', $dotationimobilisation125, $i);
        CodeEdiValeurCelluleLigne('1084',$dotationimobilisation126, $i);
        CodeEdiValeurCelluleLigne('1085',$cumul16, $i);
        CodeEdiValeurCelluleLigne('1086', $dotationimobilisation127, $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Batiments', $i);
        CodeEdiValeurCelluleLigne('1078', $dotationimobilisation128, $i);
        CodeEdiValeurCelluleLigne('1079', $dotationimobilisation129, $i);
        CodeEdiValeurCelluleLigne('1080', $dotationimobilisation130, $i);
        CodeEdiValeurCelluleLigne('1081', $dotationimobilisation131, $i);
        CodeEdiValeurCelluleLigne('1082', $dotationimobilisation132, $i);
        CodeEdiValeurCelluleLigne('1083', $dotationimobilisation133, $i);
        CodeEdiValeurCelluleLigne('1084',$dotationimobilisation134, $i);
        CodeEdiValeurCelluleLigne('1085',$cumul17, $i);
        CodeEdiValeurCelluleLigne('1086', $dotationimobilisation135, $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Constructions sur terrains d\'autrui', $i);
        CodeEdiValeurCelluleLigne('1078', $dotationimobilisation136, $i);
        CodeEdiValeurCelluleLigne('1079', $dotationimobilisation137, $i);
        CodeEdiValeurCelluleLigne('1080', $dotationimobilisation138, $i);
        CodeEdiValeurCelluleLigne('1081', $dotationimobilisation139, $i);
        CodeEdiValeurCelluleLigne('1082', $dotationimobilisation140, $i);
        CodeEdiValeurCelluleLigne('1083', $dotationimobilisation141, $i);
        CodeEdiValeurCelluleLigne('1084',$dotationimobilisation142, $i);
        CodeEdiValeurCelluleLigne('1085',$cumul18, $i);
        CodeEdiValeurCelluleLigne('1086', $dotationimobilisation143, $i);
        $i++;
        $j=144;
        CodeEdiValeurCelluleLigne('10061', 'Ouvrages d\'infrastructure', $i);
        CodeEdiValeurCelluleLigne('1078',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1079',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1080', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1081', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1082', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1083', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1084',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1085',$cumul19, $i);
        CodeEdiValeurCelluleLigne('1086', (${'dotationimobilisation' . $j++}), $i);
        
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Agencements et amenag des constructions', $i);
        CodeEdiValeurCelluleLigne('1078',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1079',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1080', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1081', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1082', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1083', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1084',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1085',$cumul20, $i);
        CodeEdiValeurCelluleLigne('1086', (${'dotationimobilisation' . $j++}), $i);
        
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Autres constructions', $i);
        CodeEdiValeurCelluleLigne('1078',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1079',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1080', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1081', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1082', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1083', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1084',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1085',$cumul21, $i);
        CodeEdiValeurCelluleLigne('1086', (${'dotationimobilisation' . $j++}), $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Installations techniques', $i);
        CodeEdiValeurCelluleLigne('1078',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1079',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1080', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1081', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1082', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1083', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1084',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1085',$cumul22, $i);
        CodeEdiValeurCelluleLigne('1086', (${'dotationimobilisation' . $j++}), $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Materiel et outillage', $i);
        CodeEdiValeurCelluleLigne('1078',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1079',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1080', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1081', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1082', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1083', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1084',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1085',$cumul23, $i);
        CodeEdiValeurCelluleLigne('1086', (${'dotationimobilisation' . $j++}), $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Emballages recuperables identifiables', $i);
        CodeEdiValeurCelluleLigne('1078',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1079',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1080', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1081', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1082', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1083', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1084',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1085',$cumul24, $i);
        CodeEdiValeurCelluleLigne('1086', (${'dotationimobilisation' . $j++}), $i);
        $i++;
       
        CodeEdiValeurCelluleLigne('10061', 'Autres instal techniques, mat. et outillage', $i);
        CodeEdiValeurCelluleLigne('1078',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1079',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1080', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1081', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1082', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1083', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1084',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1085',$cumul25, $i);
        CodeEdiValeurCelluleLigne('1086', (${'dotationimobilisation' . $j++}), $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Materiel de transport', $i);
        CodeEdiValeurCelluleLigne('1078',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1079',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1080', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1081', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1082', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1083', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1084',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1085',$cumul26, $i);
        CodeEdiValeurCelluleLigne('1086', (${'dotationimobilisation' . $j++}), $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Mobilier de bureau', $i);
        CodeEdiValeurCelluleLigne('1078',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1079',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1080', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1081', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1082', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1083', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1084',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1085',$cumul27, $i);
        CodeEdiValeurCelluleLigne('1086', (${'dotationimobilisation' . $j++}), $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Materiel de bureau', $i);
        CodeEdiValeurCelluleLigne('1078',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1079',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1080', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1081', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1082', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1083', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1084',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1085',$cumul28, $i);
        CodeEdiValeurCelluleLigne('1086', (${'dotationimobilisation' . $j++}), $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Materiel informatique', $i);
        CodeEdiValeurCelluleLigne('1078',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1079',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1080', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1081', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1082', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1083', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1084',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1085',$cumul29, $i);
        CodeEdiValeurCelluleLigne('1086', (${'dotationimobilisation' . $j++}), $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Agencements installations et aménagements divers', $i);
        CodeEdiValeurCelluleLigne('1078',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1079',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1080', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1081', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1082', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1083', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1084',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1085',$cumul30, $i);
        CodeEdiValeurCelluleLigne('1086', (${'dotationimobilisation' . $j++}), $i);
        $i++;
        CodeEdiValeurCelluleLigne('10061', 'Autres immobilisations corporelles', $i);
        CodeEdiValeurCelluleLigne('1078',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1079',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1080', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1081', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1082', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1083', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1084',(${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCelluleLigne('1085',$cumul31, $i);
        CodeEdiValeurCelluleLigne('1086', (${'dotationimobilisation' . $j++}), $i);
        CodeEdiValeurCellule('1087','');
        CodeEdiValeurCellule('1088',$totalTb1);
        CodeEdiValeurCellule('1089',$totalTb2);
        CodeEdiValeurCellule('1090',$totalTb3);
         CodeEdiValeurCellule('1091','');
        CodeEdiValeurCellule('1092','');
        CodeEdiValeurCellule('1093',$totalTb4);
        CodeEdiValeurCellule('1094',$totalTb5);
        CodeEdiValeurCellule('1095','');

        $extraFieldvaleurs = $dom->createElement('extraFieldvaleurs');
        $ValeursTableau->appendChild($extraFieldvaleurs);
        CodeextraFieldvaleurs('22','22');
        CodeextraFieldvaleurs('50','50');
        CodeextraFieldvaleurs('51','51');
        CodeextraFieldvaleurs('52','52');
       

    }
    // } else {
    //     echo "Error: The file $filename does not exist.";
    // }



?>
  


